//
// Generated by Bluespec Compiler, version 2023.07 (build 0eb551d)
//
// On Mon Jul 20 02:59:09 UTC 2026
//
//
// Ports:
// Name                         I/O  size props
// RDY_ma_start                   O     1
// mav_result                     O    65
// RDY_mav_result                 O     1 const
// RDY_ma_set_flush               O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
// ma_start_dividend              I    64
// ma_start_divisor               I    64
// ma_start_opcode                I     4
// ma_start_funct3                I     3
// ma_set_flush_c                 I     1
// EN_ma_start                    I     1
// EN_ma_set_flush                I     1
// EN_mav_result                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mk_non_restoring_divider(CLK,
				RST_N,

				ma_start_dividend,
				ma_start_divisor,
				ma_start_opcode,
				ma_start_funct3,
				EN_ma_start,
				RDY_ma_start,

				EN_mav_result,
				mav_result,
				RDY_mav_result,

				ma_set_flush_c,
				EN_ma_set_flush,
				RDY_ma_set_flush);
  input  CLK;
  input  RST_N;

  // action method ma_start
  input  [63 : 0] ma_start_dividend;
  input  [63 : 0] ma_start_divisor;
  input  [3 : 0] ma_start_opcode;
  input  [2 : 0] ma_start_funct3;
  input  EN_ma_start;
  output RDY_ma_start;

  // actionvalue method mav_result
  input  EN_mav_result;
  output [64 : 0] mav_result;
  output RDY_mav_result;

  // action method ma_set_flush
  input  ma_set_flush_c;
  input  EN_ma_set_flush;
  output RDY_ma_set_flush;

  // signals for module outputs
  wire [64 : 0] mav_result;
  wire RDY_ma_set_flush, RDY_ma_start, RDY_mav_result;

  // register rg_A
  reg [64 : 0] rg_A;
  wire [64 : 0] rg_A_D_IN;
  wire rg_A_EN;

  // register rg_div_rem
  reg rg_div_rem;
  wire rg_div_rem_D_IN, rg_div_rem_EN;

  // register rg_div_sign
  reg rg_div_sign;
  wire rg_div_sign_D_IN, rg_div_sign_EN;

  // register rg_div_type
  reg rg_div_type;
  wire rg_div_type_D_IN, rg_div_type_EN;

  // register rg_dividend
  reg [64 : 0] rg_dividend;
  wire [64 : 0] rg_dividend_D_IN;
  wire rg_dividend_EN;

  // register rg_dividend1
  reg [63 : 0] rg_dividend1;
  wire [63 : 0] rg_dividend1_D_IN;
  wire rg_dividend1_EN;

  // register rg_divisor
  reg [64 : 0] rg_divisor;
  wire [64 : 0] rg_divisor_D_IN;
  wire rg_divisor_EN;

  // register rg_inter_stage
  reg [194 : 0] rg_inter_stage;
  wire [194 : 0] rg_inter_stage_D_IN;
  wire rg_inter_stage_EN;

  // register rg_rem_sign
  reg rg_rem_sign;
  wire rg_rem_sign_D_IN, rg_rem_sign_EN;

  // register rg_special_case
  reg [1 : 0] rg_special_case;
  wire [1 : 0] rg_special_case_D_IN;
  wire rg_special_case_EN;

  // register rg_state
  reg [6 : 0] rg_state;
  reg [6 : 0] rg_state_D_IN;
  wire rg_state_EN;

  // register rg_temp_dividend
  reg [63 : 0] rg_temp_dividend;
  wire [63 : 0] rg_temp_dividend_D_IN;
  wire rg_temp_dividend_EN;

  // register rg_temp_divisor
  reg [63 : 0] rg_temp_divisor;
  wire [63 : 0] rg_temp_divisor_D_IN;
  wire rg_temp_divisor_EN;

  // rule scheduling signals
  wire CAN_FIRE_RL_rl,
       CAN_FIRE_RL_rl_extra,
       CAN_FIRE_ma_set_flush,
       CAN_FIRE_ma_start,
       CAN_FIRE_mav_result,
       WILL_FIRE_RL_rl,
       WILL_FIRE_RL_rl_extra,
       WILL_FIRE_ma_set_flush,
       WILL_FIRE_ma_start,
       WILL_FIRE_mav_result;

  // inputs to muxes for submodule ports
  wire [194 : 0] MUX_rg_inter_stage_write_1__VAL_1,
		 MUX_rg_inter_stage_write_1__VAL_2;
  wire [6 : 0] MUX_rg_state_write_1__VAL_2;
  wire MUX_rg_div_sign_write_1__VAL_1,
       MUX_rg_rem_sign_write_1__VAL_1,
       MUX_rg_state_write_1__SEL_1,
       MUX_rg_state_write_1__SEL_4;

  // remaining internal signals
  reg [63 : 0] v__h1544;
  wire [129 : 0] IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d14,
		 lv_accumulator__h612,
		 lv_accumulator__h613,
		 lv_accumulator__h642;
  wire [64 : 0] IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d76,
		lv_rem___1__h1729;
  wire [63 : 0] IF_rg_div_rem_9_THEN_IF_rg_rem_sign_3_THEN_INV_ETC___d87,
		_theResult_____1_fst__h824,
		_theResult___fst__h1093,
		_theResult___fst__h1119,
		_theResult___fst__h1145,
		_theResult___fst__h895,
		_theResult___snd__h1120,
		_theResult___snd__h1146,
		_theResult___snd_fst__h1095,
		dividend___1__h898,
		dividend__h1049,
		divisor___1__h826,
		divisor__h1051,
		lv_out___1__h1752,
		lv_out___1__h1805,
		lv_result__h1755,
		lv_result__h1808,
		lv_result__h830,
		lv_result__h901,
		v__h1616,
		x__h1871,
		y__h1345;
  wire [31 : 0] ma_start_dividend_BITS_31_TO_0__q1,
		ma_start_divisor_BITS_31_TO_0__q2;
  wire x__h1523;

  // action method ma_start
  assign RDY_ma_start = rg_state == 7'd0 ;
  assign CAN_FIRE_ma_start = rg_state == 7'd0 ;
  assign WILL_FIRE_ma_start = EN_ma_start ;

  // actionvalue method mav_result
  assign mav_result = { x__h1523, x__h1871 } ;
  assign RDY_mav_result = 1'd1 ;
  assign CAN_FIRE_mav_result = 1'd1 ;
  assign WILL_FIRE_mav_result = EN_mav_result ;

  // action method ma_set_flush
  assign RDY_ma_set_flush = 1'd1 ;
  assign CAN_FIRE_ma_set_flush = 1'd1 ;
  assign WILL_FIRE_ma_set_flush = EN_ma_set_flush ;

  // rule RL_rl
  assign CAN_FIRE_RL_rl = rg_state >= 7'd2 && rg_state <= 7'd66 ;
  assign WILL_FIRE_RL_rl = CAN_FIRE_RL_rl ;

  // rule RL_rl_extra
  assign CAN_FIRE_RL_rl_extra = rg_state == 7'd1 ;
  assign WILL_FIRE_RL_rl_extra = CAN_FIRE_RL_rl_extra ;

  // inputs to muxes for submodule ports
  assign MUX_rg_state_write_1__SEL_1 = EN_ma_set_flush && !ma_set_flush_c ;
  assign MUX_rg_state_write_1__SEL_4 = EN_mav_result && x__h1523 ;
  assign MUX_rg_div_sign_write_1__VAL_1 =
	     rg_temp_divisor[63] && !rg_div_type ;
  assign MUX_rg_inter_stage_write_1__VAL_1 =
	     { 1'b0,
	       _theResult_____1_fst__h824,
	       66'd0,
	       _theResult___fst__h895 } ;
  assign MUX_rg_inter_stage_write_1__VAL_2 =
	     { rg_inter_stage[194:130],
	       IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d14[129:1],
	       !IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d14[129] } ;
  assign MUX_rg_rem_sign_write_1__VAL_1 =
	     rg_temp_dividend[63] && !rg_div_type ;
  assign MUX_rg_state_write_1__VAL_2 = rg_state + 7'd1 ;

  // register rg_A
  assign rg_A_D_IN = 65'h0 ;
  assign rg_A_EN = 1'b0 ;

  // register rg_div_rem
  assign rg_div_rem_D_IN =
	     ma_start_funct3 == 3'b110 || ma_start_funct3 == 3'b111 ;
  assign rg_div_rem_EN = EN_ma_start ;

  // register rg_div_sign
  assign rg_div_sign_D_IN =
	     WILL_FIRE_RL_rl_extra && MUX_rg_div_sign_write_1__VAL_1 ;
  assign rg_div_sign_EN = WILL_FIRE_RL_rl_extra || EN_ma_start ;

  // register rg_div_type
  assign rg_div_type_D_IN =
	     ma_start_funct3 == 3'b101 || ma_start_funct3 == 3'b111 ;
  assign rg_div_type_EN = EN_ma_start ;

  // register rg_dividend
  assign rg_dividend_D_IN = 65'h0 ;
  assign rg_dividend_EN = 1'b0 ;

  // register rg_dividend1
  assign rg_dividend1_D_IN = dividend__h1049 ;
  assign rg_dividend1_EN = EN_ma_start ;

  // register rg_divisor
  assign rg_divisor_D_IN = 65'h0 ;
  assign rg_divisor_EN = 1'b0 ;

  // register rg_inter_stage
  assign rg_inter_stage_D_IN =
	     WILL_FIRE_RL_rl_extra ?
	       MUX_rg_inter_stage_write_1__VAL_1 :
	       MUX_rg_inter_stage_write_1__VAL_2 ;
  assign rg_inter_stage_EN = WILL_FIRE_RL_rl_extra || WILL_FIRE_RL_rl ;

  // register rg_rem_sign
  assign rg_rem_sign_D_IN =
	     WILL_FIRE_RL_rl_extra && MUX_rg_rem_sign_write_1__VAL_1 ;
  assign rg_rem_sign_EN = WILL_FIRE_RL_rl_extra || EN_ma_start ;

  // register rg_special_case
  assign rg_special_case_D_IN =
	     (divisor__h1051 == 64'd0) ?
	       2'd1 :
	       ((dividend__h1049 == y__h1345 &&
		 divisor__h1051 == 64'hFFFFFFFFFFFFFFFF &&
		 ma_start_funct3 != 3'b101 &&
		 ma_start_funct3 != 3'b111) ?
		  2'd2 :
		  2'd0) ;
  assign rg_special_case_EN = EN_ma_start ;

  // register rg_state
  always@(MUX_rg_state_write_1__SEL_1 or
	  WILL_FIRE_RL_rl_extra or
	  MUX_rg_state_write_1__VAL_2 or
	  WILL_FIRE_RL_rl or MUX_rg_state_write_1__SEL_4 or EN_ma_start)
  case (1'b1)
    MUX_rg_state_write_1__SEL_1: rg_state_D_IN = 7'd0;
    WILL_FIRE_RL_rl_extra: rg_state_D_IN = MUX_rg_state_write_1__VAL_2;
    WILL_FIRE_RL_rl: rg_state_D_IN = MUX_rg_state_write_1__VAL_2;
    MUX_rg_state_write_1__SEL_4: rg_state_D_IN = 7'd0;
    EN_ma_start: rg_state_D_IN = MUX_rg_state_write_1__VAL_2;
    default: rg_state_D_IN = 7'b0101010 /* unspecified value */ ;
  endcase
  assign rg_state_EN =
	     EN_mav_result && x__h1523 ||
	     EN_ma_set_flush && !ma_set_flush_c ||
	     WILL_FIRE_RL_rl ||
	     WILL_FIRE_RL_rl_extra ||
	     EN_ma_start ;

  // register rg_temp_dividend
  assign rg_temp_dividend_D_IN = dividend__h1049 ;
  assign rg_temp_dividend_EN = EN_ma_start ;

  // register rg_temp_divisor
  assign rg_temp_divisor_D_IN = divisor__h1051 ;
  assign rg_temp_divisor_EN = EN_ma_start ;

  // remaining internal signals
  assign IF_rg_div_rem_9_THEN_IF_rg_rem_sign_3_THEN_INV_ETC___d87 =
	     rg_div_rem ?
	       (rg_rem_sign ?
		  lv_out___1__h1752 :
		  IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d76[64:1]) :
	       (rg_div_sign ? lv_out___1__h1805 : rg_inter_stage[63:0]) ;
  assign IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d14 =
	     rg_inter_stage[129] ?
	       lv_accumulator__h613 :
	       lv_accumulator__h642 ;
  assign IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d76 =
	     rg_inter_stage[129] ?
	       lv_rem___1__h1729 :
	       rg_inter_stage[129:65] ;
  assign _theResult_____1_fst__h824 =
	     (rg_temp_divisor[63] && !rg_div_type) ?
	       divisor___1__h826 :
	       rg_temp_divisor ;
  assign _theResult___fst__h1093 =
	     (ma_start_funct3 != 3'b101 && ma_start_funct3 != 3'b111) ?
	       _theResult___fst__h1119 :
	       _theResult___fst__h1145 ;
  assign _theResult___fst__h1119 =
	     { {32{ma_start_dividend_BITS_31_TO_0__q1[31]}},
	       ma_start_dividend_BITS_31_TO_0__q1 } ;
  assign _theResult___fst__h1145 = { 32'd0, ma_start_dividend[31:0] } ;
  assign _theResult___fst__h895 =
	     (rg_temp_dividend[63] && !rg_div_type) ?
	       dividend___1__h898 :
	       rg_temp_dividend ;
  assign _theResult___snd__h1120 =
	     { {32{ma_start_divisor_BITS_31_TO_0__q2[31]}},
	       ma_start_divisor_BITS_31_TO_0__q2 } ;
  assign _theResult___snd__h1146 = { 32'd0, ma_start_divisor[31:0] } ;
  assign _theResult___snd_fst__h1095 =
	     (ma_start_funct3 != 3'b101 && ma_start_funct3 != 3'b111) ?
	       _theResult___snd__h1120 :
	       _theResult___snd__h1146 ;
  assign dividend___1__h898 = lv_result__h901 + 64'd1 ;
  assign dividend__h1049 =
	     (ma_start_opcode == 4'b1110) ?
	       _theResult___fst__h1093 :
	       ma_start_dividend ;
  assign divisor___1__h826 = lv_result__h830 + 64'd1 ;
  assign divisor__h1051 =
	     (ma_start_opcode == 4'b1110) ?
	       _theResult___snd_fst__h1095 :
	       ma_start_divisor ;
  assign lv_accumulator__h612 = { rg_inter_stage[128:0], 1'd0 } ;
  assign lv_accumulator__h613 =
	     lv_accumulator__h612 + { rg_inter_stage[194:130], 65'd0 } ;
  assign lv_accumulator__h642 =
	     lv_accumulator__h612 - { rg_inter_stage[194:130], 65'd0 } ;
  assign lv_out___1__h1752 = lv_result__h1755 + 64'd1 ;
  assign lv_out___1__h1805 = lv_result__h1808 + 64'd1 ;
  assign lv_rem___1__h1729 =
	     rg_inter_stage[129:65] + rg_inter_stage[194:130] ;
  assign lv_result__h1755 =
	     ~IF_rg_inter_stage_BIT_129_THEN_rg_inter_stage__ETC___d76[63:0] ;
  assign lv_result__h1808 = ~rg_inter_stage[63:0] ;
  assign lv_result__h830 = ~rg_temp_divisor ;
  assign lv_result__h901 = ~rg_temp_dividend ;
  assign ma_start_dividend_BITS_31_TO_0__q1 = ma_start_dividend[31:0] ;
  assign ma_start_divisor_BITS_31_TO_0__q2 = ma_start_divisor[31:0] ;
  assign v__h1616 = rg_div_rem ? 64'd0 : rg_dividend1 ;
  assign x__h1523 = rg_state == 7'd67 ;
  assign x__h1871 = x__h1523 ? v__h1544 : 64'd0 ;
  assign y__h1345 =
	     (ma_start_opcode == 4'b1110) ?
	       64'hFFFFFFFF80000000 :
	       64'h8000000000000000 ;
  always@(rg_special_case or
	  IF_rg_div_rem_9_THEN_IF_rg_rem_sign_3_THEN_INV_ETC___d87 or
	  rg_div_rem or rg_dividend1 or v__h1616)
  begin
    case (rg_special_case)
      2'd1: v__h1544 = rg_div_rem ? rg_dividend1 : 64'hFFFFFFFFFFFFFFFF;
      2'd2: v__h1544 = v__h1616;
      default: v__h1544 =
		   IF_rg_div_rem_9_THEN_IF_rg_rem_sign_3_THEN_INV_ETC___d87;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        rg_A <= `BSV_ASSIGNMENT_DELAY 65'd0;
	rg_div_rem <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_div_sign <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_div_type <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_dividend <= `BSV_ASSIGNMENT_DELAY 65'd0;
	rg_dividend1 <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_divisor <= `BSV_ASSIGNMENT_DELAY 65'd0;
	rg_rem_sign <= `BSV_ASSIGNMENT_DELAY 1'd0;
	rg_special_case <= `BSV_ASSIGNMENT_DELAY 2'd0;
	rg_state <= `BSV_ASSIGNMENT_DELAY 7'd0;
	rg_temp_dividend <= `BSV_ASSIGNMENT_DELAY 64'd0;
	rg_temp_divisor <= `BSV_ASSIGNMENT_DELAY 64'd0;
      end
    else
      begin
        if (rg_A_EN) rg_A <= `BSV_ASSIGNMENT_DELAY rg_A_D_IN;
	if (rg_div_rem_EN)
	  rg_div_rem <= `BSV_ASSIGNMENT_DELAY rg_div_rem_D_IN;
	if (rg_div_sign_EN)
	  rg_div_sign <= `BSV_ASSIGNMENT_DELAY rg_div_sign_D_IN;
	if (rg_div_type_EN)
	  rg_div_type <= `BSV_ASSIGNMENT_DELAY rg_div_type_D_IN;
	if (rg_dividend_EN)
	  rg_dividend <= `BSV_ASSIGNMENT_DELAY rg_dividend_D_IN;
	if (rg_dividend1_EN)
	  rg_dividend1 <= `BSV_ASSIGNMENT_DELAY rg_dividend1_D_IN;
	if (rg_divisor_EN)
	  rg_divisor <= `BSV_ASSIGNMENT_DELAY rg_divisor_D_IN;
	if (rg_rem_sign_EN)
	  rg_rem_sign <= `BSV_ASSIGNMENT_DELAY rg_rem_sign_D_IN;
	if (rg_special_case_EN)
	  rg_special_case <= `BSV_ASSIGNMENT_DELAY rg_special_case_D_IN;
	if (rg_state_EN) rg_state <= `BSV_ASSIGNMENT_DELAY rg_state_D_IN;
	if (rg_temp_dividend_EN)
	  rg_temp_dividend <= `BSV_ASSIGNMENT_DELAY rg_temp_dividend_D_IN;
	if (rg_temp_divisor_EN)
	  rg_temp_divisor <= `BSV_ASSIGNMENT_DELAY rg_temp_divisor_D_IN;
      end
    if (rg_inter_stage_EN)
      rg_inter_stage <= `BSV_ASSIGNMENT_DELAY rg_inter_stage_D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    rg_A = 65'h0AAAAAAAAAAAAAAAA;
    rg_div_rem = 1'h0;
    rg_div_sign = 1'h0;
    rg_div_type = 1'h0;
    rg_dividend = 65'h0AAAAAAAAAAAAAAAA;
    rg_dividend1 = 64'hAAAAAAAAAAAAAAAA;
    rg_divisor = 65'h0AAAAAAAAAAAAAAAA;
    rg_inter_stage = 195'h2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA;
    rg_rem_sign = 1'h0;
    rg_special_case = 2'h2;
    rg_state = 7'h2A;
    rg_temp_dividend = 64'hAAAAAAAAAAAAAAAA;
    rg_temp_divisor = 64'hAAAAAAAAAAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (EN_mav_result && x__h1523 && rg_special_case == 2'd2)
	$display("special case signed overflow");
  end
  // synopsys translate_on
endmodule  // mk_non_restoring_divider

